### ISSUE TITLE
Is SteamCMD necessary? 

### ISSUE THREAD

**Issue by epicylon** [cyrale/project-zomboid#2]
If I just run this I get two lines of permission errors in my Docker logs. 
`[Error] Can't access your data directory. Check permissions on your mapped directory with /server-data.`

**Comment by cyrale** [comment]
I made an update to use the latest versions of Ubunutu LTS and LinuxGSM. With this modifications, server seems to work correctly.

Did you create the directory before launching the command line? If yes, could you check the permissions by executing a `chmod`?

**Comment by cyrale** [comment]
After a few tests, I run into the same error. I fix it by doing `chmod 777 server-data` that it's not a good solution. A better solution would be to execute a `chown 1000:1000 server-data`.
