### ISSUE TITLE
Environment variable for using beta branch

### ISSUE THREAD

**Issue by maxfield-allison** [cyrale/project-zomboid#4]
I'd like to have the ability to select the zomboid beta branch for the server by setting an environment variable.

**Comment by maxfield-allison** [comment]
Not a huge deal as the current Beta is without multiplayer functionality.

**Comment by maxfield-allison** [comment]
just noticed you added the variables! Thanks for the quick response, I'll do a test shortly and let you know if there are any problems.

**Comment by cyrale** [comment]
Thanks for your feedback. I don't post a reply yet because I work actually on a new version of this image and its parent cyrale/linuxgsm. More options will be available soon.

**Comment by maxfield-allison** [comment]
I didn't connect the dots that you're also contributing to linuxgsm! That's great!

**Comment by cyrale** [comment]
No, i'm not contributing to linuxgsm. This docker image of project zomboid is based on another image that I build and it give access to linuxgsm. Today this image is very limited. I want to give it more features like the ability to manage linuxgsm config files.

**Comment by cyrale** [comment]
With le latest version tagged **0.2**, you can change branch in 2 ways:

- using `SERVER_BRANCH` and/or `SERVER_BETA_PASSWORD` variables described [here](https://github.com/cyrale/project-zomboid#variables)
- overriding common and/or server configuration files using `LGSM_COMMON_CONFIG`, `LGSM_COMMON_CONFIG_FILE`, `LGSM_SERVER_CONFIG` and/or `LGSM_SERVER_CONFIG_FILE` variables described [here](https://github.com/cyrale/linuxgsm#variables)

The second method is described in the sample linked in the response of #5
