### ISSUE TITLE
Help with connecting to server from external network.

### ISSUE THREAD

**Issue by shot-codes** [cyrale/project-zomboid#7]
Hey there, I managed to get the server up and running on a remote machine that I have access to. At first I experienced the same issue that was raised in another issue with the server failing on startup due to the inability to parse IP=... Applying the workaround worked well enough to have it running. However I am a bit unsure of how to reach the server from an external network. the console spits out an external IP address but when I try with it my game client says it cannot connect to the server. I am not so sharp at networking and lack some knowledge on the subject. Do I need to configure a sort of reverse proxy or is there perhaps just something that I am overlooking?

Many thanks for your time, and cool project. :)

**Comment by cyrale** [comment]
Thank you for using this project 😉

The IP address displayed in the console is the address of the container that you can't reach directly in bridged mode. If you want to connect to your game server, you could use the IP address of your server.

**Comment by cyrale** [comment]
I made some updates to make this image more usable. Could you test the new version by updating your configuration file with 0.2.2 tag or pulling the latest.

Documentation is also updated with 2 networks mode: bridge and host.
